import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default function RootLayout(props:any) {
  return (
    <html lang="en">
      <body>
       <AppRouterCacheProvider options={{ key: 'css' }}>
          {props.children}
       </AppRouterCacheProvider>
      </body>
    </html>
  );
}
